services:
  ollama:
    image: ollama/ollama
    ports:
        - 11434:11434
    volumes:
        - ./ollama/ollama:/root/.ollama
        - ./ollama/scripts/entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    restart: always
    healthcheck:
      test: ["CMD", "test", "-f", "/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 360  # 60 minutes = 360 * 10s
      start_period: 30s
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 360
      start_period: 30s
  llm_rag:
    depends_on:
      ollama:
        condition: service_healthy
      redis:
        condition: service_healthy
    build: ./rag_service
    container_name: llm_rag
    volumes:
      - ./docs:/app/docs
      - ./secrets.env:/app/secrets.env
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    # entrypoint: ["bash"]
    entrypoint: ["sh", "entrypoint.sh"]
    environment:
      - REDIS_HOST=redis
      - OLLAMA_HOST=ollama